spring:
  kafka:
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.harsh.linkedIn.posts_service.event.PostCreatedEvent
        spring.json.type.mapping: com.harsh.linkedin.Post_Service.event.PostCreatedEvent:com.harsh.linkedIn.posts_service.event.PostCreatedEvent