spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.harsh.linkedIn.posts_service.event.PostCreatedEvent
        spring.json.type.mapping: >
          com.harsh.linkedin.Post_Service.event.PostCreatedEvent:com.harsh.linkedIn.posts_service.event.PostCreatedEvent,
          com.harsh.linkedin.connection_service.event.AcceptConnectionRequestEvent:com.harsh.linkedIn.connection_service.event.AcceptConnectionRequestEvent,
          com.harsh.linkedin.connection_service.event.SendConnectionRequestEvent:com.harsh.linkedIn.connection_service.event.SendConnectionRequestEvent