version: "3.8"

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - linkedin-network
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8090:8080
    depends_on:
      - kafka
    networks:
      - linkedin-network
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  notification-db:
    image: postgres:15
    container_name: notification-db
    ports:
      - "5434:5432" # Access via DBeaver on port 5434
    environment:
      - POSTGRES_DB=notificationDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=choudhary@3566
    networks:
      - linkedin-network
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  posts-db:
    image: postgres:15
    container_name: posts-db
    ports:
      - "5433:5432" # Access via DBeaver on port 5433
    environment:
      - POSTGRES_DB=postDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=choudhary@3566
    networks:
      - linkedin-network
    volumes:
      - posts-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres:15
    container_name: user-db
    ports:
      - "5432:5432" # Access via DBeaver on port 5432
    environment:
      - POSTGRES_DB=usersDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=choudhary@3566
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  connections-db:
    image: neo4j
    container_name: connections-db
    environment:
      - NEO4J_AUTH=neo4j/Harsh1234
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - connections-db-data:/data
    networks:
      - linkedin-network

  discovery-server:
    build:
      context: ./Discovery-Server
    image: harshchoudhary21/linkedin-app/discovery-service
    container_name: discovery-server
    networks:
      - linkedin-network
    ports:
      - "8761:8761"

  posts-service:
    build:
      context: ./Post-Service
    image: harshchoudhary21/linkedin-app/post-service
    container_name: posts-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - posts-db
      - kafka

  user-service:
    build:
      context: ./UserService
    image: harshchoudhary21/linkedin-app/user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - user-db
      - kafka

  notification-service:
    build:
      context: ./notification-service
    image: harshchoudhary21/linkedin-app/notification-service
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - notification-db
      - kafka

  connections-service:
    build:
      context: ./connection-service
    image: harshchoudhary21/linkedin-app/connection-service
    container_name: connections-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - connections-db
      - kafka

  api-gateway:
    build:
      context: ./api-gateway
    image: harshchoudhary21/linkedin-app/api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    networks:
      - linkedin-network
    depends_on:
      - discovery-server

networks:
  linkedin-network:

volumes:
  kafka_data:
  notification-db-data:
  posts-db-data:
  user-db-data:
  connections-db-data: