spring.application.name=Post-Service
server.port = 9010
server.servlet.context-path=/posts
spring.datasource.url = jdbc:postgresql://posts-db:5432/postDB
spring.datasource.username = postgres
spring.datasource.password = choudhary@3566
spring.jpa.hibernate.ddl-auto = update

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka