spring.application.name=Post-Service
server.port = 9010
spring.datasource.url = jdbc:postgresql://localhost:5432/postDB
spring.datasource.username = postgres
spring.datasource.password = choudhary@3566
spring.jpa.hibernate.ddl-auto = create-drop