spring.application.name=connection-service
server.servlet.context-path=/connections
server.port=9030

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka


spring.neo4j.uri=neo4j://connections-db:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=Harsh1234

# Optional
spring.data.neo4j.database=neo4j

